"""remove client document urls

Revision ID: 8483b31f0e4e
Revises: 758c316861b9
Create Date: 2026-06-24 09:04:28.345708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8483b31f0e4e"
down_revision: Union[str, Sequence[str], None] = "c1d0c5d0c5u1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "license_back_url")
    op.drop_column("clients", "id_document_url")
    op.drop_column("clients", "license_front_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("license_front_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column("clients", sa.Column("id_document_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column("clients", sa.Column("license_back_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
